### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by szabgab** [Tina-otoge/sssimp#5]
Hi Tina,

right now I don't see any automated tests in the package. I'd be happy to send a PR with a test that would work the following way:

Preparation:
* Generate the example (which is in the `example` branch)
* Move the results (the `output` directory) to another directory called `expected_output` and commit to git.

The test:
* The tests then would generate the example (run `PYTHONPATH=src python -m sssimp`) and then compare the results to the `expected_output`. They should be the same. [1]
* When there is some expected change, either because you changed the example input or the processing, then you'd be compare to the able to compare to the earlier output and if you are satisfied you could update the expected_output from the actual output.

Once this is working I'd enable GitHub Actions to run it on every change.

[1] I checked and they are not the same as the order in the `ul` seems to be random. Though it is an "ul = unordered list", but I think in most cases people would expect consistency in the resulting order.

**Comment by Tina-otoge** [comment]
Hello and thank you for your interest in my project.

Indeed it is currently missing automated tests, and it is something I would like to add in the future, so any help on that front is welcome.

The `example` branch as it is right now is quite lagging behind, I did not keep track of what was added since then, but I'm most certainly sure it does not showcase all of the features *sssimp* has, so keep that in mind if you plan to use it as a base for writing tests.

There are still quite a few features that I had envisioned and are still missing, and depending on how I go about them, I may need to do breaking changes, that's why I haven't really looked into setting up tests yet, I do not want them to become too much of a bother with changes happening often, until I get the tool to be stable and ready.

The end goal for tests should be for them to double act as documentation to showcase what this tool can achieve. Integrating them into a documentation generator tool would be the best, but a simple comparison as you are suggesting would be a good compromise until the tool is more stable. You are more than welcome to submit a PR with this.
